export const files = [
  {
    name: "Components",
    isFolder: true,
    level:1,
    location:"0",
    children: [
      {
        name: "FileExplorer",
        isFolder: true,
        location:"00",
        children: [
          {
            name: "FileExplore.jsx",
            location:"000",
            isFolder: false,
            children: [],
          },
        ],
      },
    ],
  },
  {
    name: "Hoc",
    isFolder: true,
    level:1,
    location:"1",
    children: [
      {
        name: "LoggerHoc",
        isFolder: true,
        location:"10",
        children: [
          {
            name: "Logger.jsx",
            isfolder: false,
            location:"100",
            children: [],
          },
        ],
      },
      {
        name: "AuthHoc",
        isFolder: true,
        location:"11",
        children: [
          {
            name: "IsAuth.jsx",
            isfolder: false,
            location:"110",
            children: [],
          },
        ],
      },
    ],
  },
  {
    name: "package.json",
    isFolder: false,
    level:1,
    location:"2",
    children: [],
  },
  {
    name: "package-lock.json",
    isFolder: false,
    level:1,
    location:"3",
    children: [],
  },
];
export const countryList= [
  {"label": "Afghanistan", "value": "AF"},
  {"label": "Albania", "value": "AL"},
  {"label": "Algeria", "value": "DZ"},
  {"label": "Andorra", "value": "AD"},
  {"label": "Angola", "value": "AO"},
  {"label": "Antigua and Barbuda", "value": "AG"},
  {"label": "Argentina", "value": "AR"},
  {"label": "Armenia", "value": "AM"},
  {"label": "Australia", "value": "AU"},
  {"label": "Austria", "value": "AT"},
  {"label": "Azerbaijan", "value": "AZ"},
  {"label": "Bahamas", "value": "BS"},
  {"label": "Bahrain", "value": "BH"},
  {"label": "Bangladesh", "value": "BD"},
  {"label": "Barbados", "value": "BB"},
  {"label": "Belarus", "value": "BY"},
  {"label": "Belgium", "value": "BE"},
  {"label": "Belize", "value": "BZ"},
  {"label": "Benin", "value": "BJ"},
  {"label": "Bhutan", "value": "BT"},
  {"label": "Bolivia", "value": "BO"},
  {"label": "Bosnia and Herzegovina", "value": "BA"},
  {"label": "Botswana", "value": "BW"},
  {"label": "Brazil", "value": "BR"},
  {"label": "Brunei", "value": "BN"},
  {"label": "Bulgaria", "value": "BG"},
  {"label": "Burkina Faso", "value": "BF"},
  {"label": "Burundi", "value": "BI"},
  {"label": "Cabo Verde", "value": "CV"},
  {"label": "Cambodia", "value": "KH"},
  {"label": "Cameroon", "value": "CM"},
  {"label": "Canada", "value": "CA"},
  {"label": "Central African Republic", "value": "CF"},
  {"label": "Chad", "value": "TD"},
  {"label": "Chile", "value": "CL"},
  {"label": "China", "value": "CN"},
  {"label": "Colombia", "value": "CO"},
  {"label": "Comoros", "value": "KM"},
  {"label": "Congo, Democratic Republic of the", "value": "CD"},
  {"label": "Congo, Republic of the", "value": "CG"},
  {"label": "Costa Rica", "value": "CR"},
  {"label": "Croatia", "value": "HR"},
  {"label": "Cuba", "value": "CU"},
  {"label": "Cyprus", "value": "CY"},
  {"label": "Czech Republic", "value": "CZ"},
  {"label": "Denmark", "value": "DK"},
  {"label": "Djibouti", "value": "DJ"},
  {"label": "Dominica", "value": "DM"},
  {"label": "Dominican Republic", "value": "DO"},
  {"label": "Ecuador", "value": "EC"},
  {"label": "Egypt", "value": "EG"},
  {"label": "El Salvador", "value": "SV"},
  {"label": "Equatorial Guinea", "value": "GQ"},
  {"label": "Eritrea", "value": "ER"},
  {"label": "Estonia", "value": "EE"},
  {"label": "Eswatini", "value": "SZ"},
  {"label": "Ethiopia", "value": "ET"},
  {"label": "Fiji", "value": "FJ"},
  {"label": "Finland", "value": "FI"},
  {"label": "France", "value": "FR"},
  {"label": "Gabon", "value": "GA"},
  {"label": "Gambia", "value": "GM"},
  {"label": "Georgia", "value": "GE"},
  {"label": "Germany", "value": "DE"},
  {"label": "Ghana", "value": "GH"},
  {"label": "Greece", "value": "GR"},
  {"label": "Grenada", "value": "GD"},
  {"label": "Guatemala", "value": "GT"},
  {"label": "Guinea", "value": "GN"},
  {"label": "Guinea-Bissau", "value": "GW"},
  {"label": "Guyana", "value": "GY"},
  {"label": "Haiti", "value": "HT"},
  {"label": "Honduras", "value": "HN"},
  {"label": "Hungary", "value": "HU"},
  {"label": "Iceland", "value": "IS"},
  {"label": "India", "value": "IN"},
  {"label": "Indonesia", "value": "ID"},
  {"label": "Iran", "value": "IR"},
  {"label": "Iraq", "value": "IQ"},
  {"label": "Ireland", "value": "IE"},
  {"label": "Israel", "value": "IL"},
  {"label": "Italy", "value": "IT"},
  {"label": "Jamaica", "value": "JM"},
  {"label": "Japan", "value": "JP"},
  {"label": "Jordan", "value": "JO"},
  {"label": "Kazakhstan", "value": "KZ"},
  {"label": "Kenya", "value": "KE"},
  {"label": "Kiribati", "value": "KI"},
  {"label": "Korea, North", "value": "KP"},
  {"label": "Korea, South", "value": "KR"},
  {"label": "Kosovo", "value": "XK"},
  {"label": "Kuwait", "value": "KW"},
  {"label": "Kyrgyzstan", "value": "KG"},
  {"label": "Laos", "value": "LA"},
  {"label": "Latvia", "value": "LV"},
  {"label": "Lebanon", "value": "LB"},
  {"label": "Lesotho", "value": "LS"},
  {"label": "Liberia", "value": "LR"},
  {"label": "Libya", "value": "LY"},
  {"label": "Liechtenstein", "value": "LI"},
  {"label": "Lithuania", "value": "LT"},
  {"label": "Luxembourg", "value": "LU"},
  {"label": "Madagascar", "value": "MG"}
]
